// use crate::{components::App, 
use constants::{SkinsetId, ChampId};
use log::{info, Level};
use components::app::App;

mod components;
mod constants;
mod model;

/// Content generated by the build script.
mod generated {
    include!(concat!(env!("OUT_DIR"), "/generated.rs"));
}

fn main() {
    // Set the panic handler to be the browser's `console.error`.
    console_error_panic_hook::set_once();
    // Initialize the logger.
    console_log::init_with_level(Level::Debug).expect("error initializing logger");

    // Log some info. 
    info!("Logger started");
    info!("Max Skinset ID available: {:?}", SkinsetId::MAX);
    info!("Max Champ ID available: {:?}", ChampId::MAX);
    
    // Mount/start the main App.
    leptos::mount_to_body(App);
}
