use crate::components::App;
use log::{info, Level};

mod components;
mod constants;

/// Content generated by the build script.
mod generated {
    include!(concat!(env!("OUT_DIR"), "/generated.rs"));
}

fn main() {
    // Initialize the logger.
    console_log::init_with_level(Level::Info).expect("error initializing logger");
    info!("Logger started");
    // Start the yew global renderer -- this kicks off a loading bar to wait for everything to initialize.
    yew::Renderer::<App>::new().render();
}
